[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "DetailLogger"
version = "0.1.3"
description = "Styled console printing made simple — color, format, and clarity in one package."
readme = "README.md"
authors = [{ name="Ryan LaPine", email="github.stunt845@passinbox.com" }]
license = { text = "MIT" }
requires-python = ">=3.7"
dependencies = [] 

[project.urls]
Homepage = "https://github.com/rlapine/DetailLogger"
Repository = "https://github.com/rlapine/DetailLogger"
Issues = "https://github.com/rlapine/DetailLogger/issues"

[project.scripts]
detaillogger = "detaillogger.detaillogger:main"

[project.classifiers]
# Full list: https://pypi.org/classifiers/
"Programming Language :: Python :: 3"
"License :: OSI Approved :: MIT License"
"Operating System :: OS Independent"
"Intended Audience :: Developers"
"Topic :: Software Development :: Libraries"
"Topic :: Utilities"